#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
RESET='\033[0m'

BINARY=bin/defuse
TEST_DIR=test/*
OUTPUT_TMP=tmp/hello_world

good() {
  echo -e "${GREEN}${1}${RESET}"
}

bad() {
  echo -e "${RED}${1}${RESET}"
}

set -e

if ! [[ -d "$TEST_DIR" ]]; then
  bad "[-] Test folder '$TEST_DIR' does not exist - Note that for multiple reasons, testing bombs shouldn't be shared over public repo."
  bad "If you are a developer, you should have this folder already."
  bad "If you are not, we are always looking for more samples to further improve the solver."
  exit 1
fi

good "[*] Recompiling stuffs"
make remake

for f in "$TEST_DIR"; do
  good "[*] Processing $f"

  "$BINARY" "$f" 2>&1 1>/dev/null | tee "$OUTPUT_TMP"

  if [ $? -ne 0 ]; then
    bad "Unit test failed: Solver exit with status non-zero."
    continue
  fi

  if grep -q 'ERROR' "$OUTPUT_TMP"; then
    bad "Unit test failed: Solver can't find the solution."
    continue
  fi

  good "Unit test passed."

  rm -f "$OUTPUT_TMP"
done
